name: Build LaTeX document
on: [push]
jobs:
  build_latex:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Git Repo
          uses: actions/checkout@v2
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with: 
            name: resume
            path: main.pdf
  deploy_main:
    needs: build_latex
    runs-on: ubuntu-latest
    steps:
    - name: Download PDF
      uses: actions/download-artifact@v2
      with:
          name: resume
    - name: Deploy PDF
      uses: burnett01/rsync-deployments@5.1
      with:
          name: resume
    - name: Deploy PDF
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -av --progress
        path: ./main.pdf
        remote_path: /var/www/resume.pdf
        remote_host: ${{ secrets.DEPLOY_HOSTNAME }}
        remote_user: ${{ secrets.DEPLOY_USERNAME }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
