name: Build LaTeX document
on:
  push:
    branches:
      - upload
jobs:
  deploy_main:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git Repo
      uses: actions/checkout@v2
    - name: Download PDF
      uses: actions/download-artifact@v3
      with:
          name: resume.pdf
    - name: Deploy PDF
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -av --progress
        path: ./resume.pdf
        remote_path: /var/www/resume/resume.pdf
        remote_host: ${{ secrets.DEPLOY_HOSTNAME }}
        remote_user: ${{ secrets.DEPLOY_USERNAME }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
